ingress:
  enabled: false

env:
  - name: HORUSEC_PORT
    value: "8003"
  - name: HORUSEC_SWAGGER_HOST
    value: 0.0.0.0
  - name: HORUSEC_MANAGER_URL
    value: http://horus-dev.zup.com.br
  - name: HORUSEC_BROKER_HOST
    value: rabbitmq
  - name: HORUSEC_BROKER_PORT
    value: "5672"
  - name: HORUSEC_DATABASE_SQL_LOG_MODE
    value: "false"
  - name: HORUSEC_GRPC_AUTH_URL
    value: auth-horusec-auth-helm:8007
  - name: HORUSEC_GRPC_USE_CERTS
    value: "false"

envFromSecret:
  - name: HORUSEC_BROKER_USERNAME
    key: broker-username
  - name: HORUSEC_BROKER_PASSWORD
    key: broker-password
  - name: HORUSEC_DATABASE_SQL_URI
    key: database-uri
  - name: HORUSEC_JWT_SECRET_KEY
    key: jwt-token