image:
  repository: 671982376808.dkr.ecr.us-east-1.amazonaws.com/horusec-auth
  pullPolicy: IfNotPresent

ingress:
  enabled: false

env:
  - name: HORUSEC_SWAGGER_HOST
    value: 0.0.0.0
  - name: HORUSEC_PORT
    value: "8006"
  - name: HORUSEC_DATABASE_SQL_DIALECT
    value: postgres
  - name: HORUSEC_DATABASE_SQL_LOG_MODE
    value: "false"
  - name: HORUSEC_GRPC_PORT
    value: "8007"
  - name: HORUSEC_GRPC_USE_CERTS
    value: "false"
  - name: HORUSEC_BROKER_HOST
    value: rabbitmq.horus-dev.svc.cluster.local
  - name: HORUSEC_BROKER_PORT
    value: "5672"
  - name: HORUSEC_DISABLED_BROKER
    value: "false"
  - name: HORUSEC_AUTH_TYPE
    value: horusec
  - name: HORUSEC_ENABLE_APPLICATION_ADMIN
    value: "false"
  - name: HORUSEC_BROKER_HOST
    value: rabbitmq.horus-dev.svc.cluster.local
  - name: HORUSEC_BROKER_PORT
    value: "5672"
